python run_experiment.py -i 0 &
python run_experiment.py -i 1 &
python run_experiment.py -i 2 &
python run_experiment.py -i 3 &
python run_experiment.py -i 4 &
python run_experiment.py -i 5 &
python run_experiment.py -i 6 &
python run_experiment.py -i 7 &
python run_experiment.py -i 8 &
python run_experiment.py -i 9 &
python run_experiment.py -i 10 &
python run_experiment.py -i 11 &
python run_experiment.py -i 12 &
python run_experiment.py -i 13 &
python run_experiment.py -i 14 &
python run_experiment.py -i 15 &
python run_experiment.py -i 16 &
python run_experiment.py -i 17 &
python run_experiment.py -i 18 &
python run_experiment.py -i 19 &
python run_experiment.py -i 20 &
python run_experiment.py -i 21 &
python run_experiment.py -i 22 &
python run_experiment.py -i 23 &
python run_experiment.py -i 24 &
python run_experiment.py -i 25 &
python run_experiment.py -i 26 &
python run_experiment.py -i 27 &
python run_experiment.py -i 28 &
python run_experiment.py -i 29 &
python run_experiment.py -i 30 &
python run_experiment.py -i 31 &
python run_experiment.py -i 32 &
python run_experiment.py -i 33 &
python run_experiment.py -i 34 &
python run_experiment.py -i 35 &
python run_experiment.py -i 36 &
python run_experiment.py -i 37 &
python run_experiment.py -i 38 &
python run_experiment.py -i 39 &
python run_experiment.py -i 40 &
python run_experiment.py -i 41 &
python run_experiment.py -i 42 &
python run_experiment.py -i 43 &
python run_experiment.py -i 44 &
python run_experiment.py -i 45 &
python run_experiment.py -i 46 &
python run_experiment.py -i 47 &
python run_experiment.py -i 48 &
python run_experiment.py -i 49 &
python run_experiment.py -i 50 &
python run_experiment.py -i 51 &
python run_experiment.py -i 52 &
python run_experiment.py -i 53 &
python run_experiment.py -i 54 &
python run_experiment.py -i 55 &
python run_experiment.py -i 56 &
python run_experiment.py -i 57 &
python run_experiment.py -i 58 &
python run_experiment.py -i 59 &
python run_experiment.py -i 60 &
python run_experiment.py -i 61 &
python run_experiment.py -i 62 &
python run_experiment.py -i 63 &
python run_experiment.py -i 64 &
python run_experiment.py -i 65 &
python run_experiment.py -i 66 &
python run_experiment.py -i 67 &
python run_experiment.py -i 68 &
python run_experiment.py -i 69 &
python run_experiment.py -i 70 &
python run_experiment.py -i 71 &
python run_experiment.py -i 72 &
python run_experiment.py -i 73 &
python run_experiment.py -i 74 &
python run_experiment.py -i 75 &
python run_experiment.py -i 76 &
python run_experiment.py -i 77 &
python run_experiment.py -i 78 &
python run_experiment.py -i 79 &
python run_experiment.py -i 80 &