python run_experiment.py -i 54 &
python run_experiment.py -i 55 &
python run_experiment.py -i 56 &
python run_experiment.py -i 57 &
python run_experiment.py -i 58 &
python run_experiment.py -i 59 &
python run_experiment.py -i 60 &
python run_experiment.py -i 61 &
python run_experiment.py -i 62 &
python run_experiment.py -i 63 &
python run_experiment.py -i 64 &
python run_experiment.py -i 65 &
python run_experiment.py -i 66 &
python run_experiment.py -i 67 &
python run_experiment.py -i 68 &
python run_experiment.py -i 69 &
python run_experiment.py -i 70 &
python run_experiment.py -i 71 &
python run_experiment.py -i 72 &
python run_experiment.py -i 73 &
python run_experiment.py -i 74 &
python run_experiment.py -i 75 &
python run_experiment.py -i 76 &
python run_experiment.py -i 77 &
python run_experiment.py -i 78 &
python run_experiment.py -i 79 &
python run_experiment.py -i 80 &